name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
            KOLEO_EMAIL: ${{ secrets.KOLEO_EMAIL }}
            KOLEO_PASSWORD: ${{ secrets.KOLEO_PASSWORD }}
            KOLEO_GRANT_TYPE: ${{ secrets.KOLEO_GRANT_TYPE }}
            KOLEO_CLIENT_ID: ${{ secrets.KOLEO_CLIENT_ID }}
        run: npm test
        